### ISSUE TITLE
Exposed api key

### ISSUE THREAD

**Issue by hendrawd** [RowlandOti/MovieSquire#1]
Hi @RowlandOti , actually you exposed your API key in https://github.com/RowlandOti/MovieSquire/blob/master/app/build.gradle#L35
https://github.com/RowlandOti/MovieSquire/blob/master/app/build.gradle#L45.
Although themoviedb.org is a free service, and they don't have any particular regulation about it, but don't you think it is better to hide it?
Also one of udacity requirement from popular movie project is:
`IMPORTANT: If you're submitting via a public Github repository, please make sure any external API key that you utilize, has been removed from your code. It's highly unsafe (and often breaks the Terms of Service) to include API keys in public repos, so you need to remove yours. You can add a note in a README file where a reviewer should go to insert their API key. Reviewers have been trained to expect this situation.`

**Comment by RowlandOti** [comment]
Hi, @hendrawd  thanks for the heads up on that. I didn't see that, but I have fixed it with a commit.

**Comment by hendrawd** [comment]
but i could still browse the previous project state like https://github.com/RowlandOti/MovieSquire/blob/405ad9a2d2b7305cd39286708ab6b8803016fa08/app/build.gradle#L35 and see the api key from there 😝
